### PR TITLE
added a section about squirrels to the readme

### PR DESCRIPTION
**Pull request by mikelikesbikes**
This is super important for everyone to see... and makes Mike real
happy.

### CODE REVIEW

**Comment by ryanbriones** [comment]
Looks pretty good :squirrel:

**Comment by mikelikesbikes** [comment]
:smoking::fish:

**Comment by mikelikesbikes** [comment]
:+1:

**Comment by ryanbriones** [comment]
:-1:

**Comment by mikelikesbikes** [comment]
How DARE you!

**Pull request merged**
